### ISSUE TITLE
Do not print empty sections

### ISSUE THREAD

**Issue by sobolevn** [jeromepin/whale-linter#20]
Right now when I run `whale-linter`, this is what I get:

```
» whale-linter docker/django/Dockerfile

docker/django/Dockerfile

CRITICAL :

WARNING :
  22: BadPractice : Prefer 'COPY' over 'ADD' for adding files and directories to a container. 'ADD' sounds to much magic

ENHANCEMENT :


```

That's nice, but I don't really need to see empty sections. So, I think that UX could be improved.

**Comment by sobolevn** [comment]
Any feedback, please?

**Comment by jeromepin** [comment]
I was waiting the week-end to work on that. It's fixed now.

**Comment by sobolevn** [comment]
Nice, thanks!
