### ISSUE TITLE
using docker itself?

### ISSUE THREAD

**Issue by fruitl00p** [jeromepin/whale-linter#6]
First off: great way to centralize the "best practices" regarding the Dockerfiles! Always a great move!

I would have expected to be able to run this using a docker image itself in order not to have to download / build it manually... Any chance you will publish a public image on the hub?

It would increase the ease of use (and you could "eat your own dogfood" by checking your own `Dockerfile` :smile: )

**Comment by jeromepin** [comment]
Of course ! I'm currently building it :smile:
And obviously I will run whale-linter against it :smile:

**Comment by jeromepin** [comment]
The image is now on the [Docker Hub](https://hub.docker.com/r/jeromepin/whale-linter/), building automatically on every push.
