### ISSUE TITLE
cleanup of apt line fails to be recognized?

### ISSUE THREAD

**Issue by fruitl00p** [jeromepin/whale-linter#7]
using the following test `Dockerfile`

```
FROM ubuntu:14.04
MAINTAINER Kingsquare <docker@kingsquare.nl>
# just test the cleanup
RUN apt-get clean && \
    rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/*
```

It still procuces the following output: `docker run -it --rm -v $(pwd)/Dockerfile:/Dockerfile jeromepin/whale-linter`

``` shell
/Dockerfile

CRITICAL :

WARNING :

ENHANCEMENT :
      BestPractice    : Consider removing APT cache : 'rm -rf /var/lib/apt/lists/*' after line 4
```

I've even tried to have multiple `rm` lines, but to no avail?

**Comment by jeromepin** [comment]
Thanks for your feedback :smiley: 

Multiline commands always give me troubles and headaches. This bug comes from bad handling of line number. I'm working on it :smile:

**Comment by jeromepin** [comment]
This should be fixed now and the docker image has been updated (it is now based on github's version instead of the one coming from PyPI)

**Comment by fruitl00p** [comment]
Awesome, confirmed it works! :+1:
