### ISSUE TITLE
Bad handling of multiline when there is only packages names.

### ISSUE THREAD

**Issue by jeromepin** [jeromepin/whale-linter#9]
As described by [Docker's guidelines](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/sort-multi-line-arguments) : 

``` bash
apt-get install -y --no-install-recommends \                                                                                                                                                                                           
 cron=3.0pl1-124ubuntu2
```

Throws - for now - 

```
ENHANCEMENT :
  9: Immutability    : A version should be specified for the package '
' in order to improve immutability
  9: Immutability    : A version should be specified for the package '
' in order to improve immutability
  9: Maintainability : Consider sorting APT packages for better reading

```

**Comment by obihann** [comment]
Any progress on this, I'm still getting it many months later.

**Comment by jeromepin** [comment]
I'm planning on a big release which should correct this. It will make use of small third parties libraries to do the parsing stuff, letting me focus on the analysis part. Unfortunately, I have not much time to do it...

**Comment by jeromepin** [comment]
@obihann This issue should be fixed now. Package has been updated on PyPi and Docker Hub.
